services:
  app:
    image: phonebook-frontend
    build:
      context: ./phonebook-frontend
      dockerfile: Dockerfile
    volumes:
      - ./phonebook-frontend:/usr/src/app
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: personsdb
    volumes:
      - ./phonebook-backend/mongo_data:/data/db
      - ./phonebook-backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  server:
    image: phonebook-server
    build:
      context: ./phonebook-backend
      dockerfile: Dockerfile
    volumes:
      - ./phonebook-backend:/usr/src/app
    environment:
      MONGO_URL: mongodb://mongoadmin:secret@mongo:27017/personsdb
    depends_on:
      - mongo

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
